# 라이브러리 설치

In [1]:
!python -m pip install numpy pandas

Requirement already satisfied: numpy in f:\Projects\20260617\.venv\Lib\site-packages (2.4.6)
Requirement already satisfied: pandas in f:\Projects\20260617\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in f:\Projects\20260617\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in f:\Projects\20260617\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in f:\Projects\20260617\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# 라이브러리 임포트

In [2]:
import numpy as np
import pandas as pd

# 데이터 전처리

## 데이터를 읽어들여 데이터 프레임 만들기

In [3]:
# data 디렉토리에 다음과 같이 4개의 파일이 필요하기 때문에
# meteorshowers-data.zip 압축 파일을 data 디렉토리에서 압축 해제 한다.

# meteorshowers.csv - 유성우 데이터
# moonphases.csv - 달의 위상 데이터
# constellations.csv - 별자리 데이터
# cities.csv - 주요 도시들의 위도 데이터

In [4]:
# 데이터셋 불러오기
meteor_showers = pd.read_csv('../data/meteorshowers.csv')
moon_phases = pd.read_csv('../data/moonphases.csv')
constellations = pd.read_csv('../data/constellations.csv')
cities = pd.read_csv('../data/cities.csv')

## 유성우 데이터

In [5]:
# 유성우 데이터 확인하기
meteor_showers.head()

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"

## 달의 위상 데이터

In [6]:
# 달의 위상 데이터 확인하기
moon_phases.head()

     month  day      moonphase specialevent
0  january    1            NaN          NaN
1  january    2  first quarter          NaN
2  january    3            NaN          NaN
3  january    4            NaN          NaN
4  january    5            NaN          NaN

## 별자리 데이터

In [7]:
# 별자리 데이터 확인하기
constellations.head()

  constellation bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra    august             90          -40    21:00   northern
1      Aquarius   october             65          -90    21:00   southern
2         Orion   january             85          -75    21:00   northern
3       Perseus  december             90          -35    21:00   northern
4           Leo     april             90           65    21:00   northern

## 도시 데이터

In [8]:
# 도시 데이터 확인하기
cities.head()

          city  latitude               country
0    Abu Dhabi     24.47  United Arab Emirates
1        Abuja      9.07               Nigeria
2        Accra      5.55                 Ghana
3    Adamstown    -25.07      Pitcairn Islands
4  Addis Ababa      9.02              Ethiopia

## 컬럼 타입 변경 - 월(month) 이름을 숫자로 변경

### 유성우 데이터 프레임

In [9]:
# meteor_showers 유성우 정보 조회
meteor_showers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 5 non-null      str
 1   radiant              5 non-null      str
 2   bestmonth            5 non-null      str
 3   startmonth           5 non-null      str
 4   startday             5 non-null      int64
 5   endmonth             5 non-null      str
 6   endday               5 non-null      int64
 7   hemisphere           5 non-null      str
 8   preferredhemisphere  5 non-null      str
dtypes: int64(2), str(7)
memory usage: 492.0 bytes

In [10]:
meteor_showers['bestmonth'].unique()

<StringArray>
['april', 'may', 'october', 'august', 'november']
Length: 5, dtype: str

In [11]:
# 월명을 숫자로 변환하기 위한 딕셔너리 생성 months
months = {'january': 1, 'february': 2, 'march': 3, 'april': 4, 'may': 5, 'june': 6,
          'july': 7, 'august': 8, 'september': 9, 'october': 10, 'november': 11, 'december': 12}

In [12]:
# 월명을 숫자로 변환하기 위한 딕셔너리 생성 months
from datetime import datetime

months = { datetime(2026, i, 1).strftime('%B').lower(): i for i in range(1, 13) }
print(months)

{'january': 1, 'february': 2, 'march': 3, 'april': 4, 'may': 5, 'june': 6, 'july': 7, 'august': 8, 'september': 9, 'october': 10, 'november': 11, 'december': 12}

In [13]:
# 월명을 숫자로 변환하는 month_mapper 함수를 람다 함수로 정의
month_mapper = lambda x: months.get(x, x)

In [14]:
# month_mapper 람다 함수 테스트
for month in months.keys():
    print(f'{month} -> {month_mapper(month)}')

january -> 1
february -> 2
march -> 3
april -> 4
may -> 5
june -> 6
july -> 7
august -> 8
september -> 9
october -> 10
november -> 11
december -> 12

In [15]:
# month_mapper 람다 함수 테스트 결과
test1 = meteor_showers['bestmonth'].map(month_mapper)
test1.isna()

0    False
1    False
2    False
3    False
4    False
Name: bestmonth, dtype: bool

In [16]:
# month_mapper 람다 함수 테스트 결과
test1.info()

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: bestmonth
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [17]:
# month_mapper 람다 함수 테스트 결과
test1

0     4
1     5
2    10
3     8
4    11
Name: bestmonth, dtype: int64

In [18]:
# 유성우 데이터 프레임의 월명을 숫자로 변환 map 메소드 사용 (bestmonth 컬럼에 month_mapper 함수 적용)
meteor_showers['bestmonth'] = meteor_showers['bestmonth'].map(month_mapper)
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,4,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,5,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,10,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,8,july,14,august,24,northern,northern
4,Leonids,Leo,11,november,6,november,30,"northern, southern","northern, southern"

In [19]:
# 유성우 데이터 프레임의 월명을 숫자로 변환 map 메소드 사용 (startmonth 컬럼에 month_mapper 함수 적용)
meteor_showers['startmonth'] = meteor_showers['startmonth'].map(month_mapper)
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,4,4,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,5,4,19,may,28,"northern, southern",southern
2,Orionids,Orion,10,10,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,8,7,14,august,24,northern,northern
4,Leonids,Leo,11,11,6,november,30,"northern, southern","northern, southern"

In [20]:
# 유성우 데이터 프레임의 월명을 숫자로 변환 map 메소드 사용 (endmonth 컬럼에 month_mapper 함수 적용)
meteor_showers['endmonth'] = meteor_showers['endmonth'].map(month_mapper)
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,4,4,21,4,22,northern,northern
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern"
3,Perseids,Perseus,8,7,14,8,24,northern,northern
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern"

In [21]:
# 유성우 데이터 프레임의 월명이 숫자로 변경되었는지 정보 확인
meteor_showers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 5 non-null      str
 1   radiant              5 non-null      str
 2   bestmonth            5 non-null      int64
 3   startmonth           5 non-null      int64
 4   startday             5 non-null      int64
 5   endmonth             5 non-null      int64
 6   endday               5 non-null      int64
 7   hemisphere           5 non-null      str
 8   preferredhemisphere  5 non-null      str
dtypes: int64(5), str(4)
memory usage: 492.0 bytes

### 달의 위상 데이터 프레임

In [22]:
# 달의 위상 데이터 확인하기
moon_phases.head()

     month  day      moonphase specialevent
0  january    1            NaN          NaN
1  january    2  first quarter          NaN
2  january    3            NaN          NaN
3  january    4            NaN          NaN
4  january    5            NaN          NaN

In [23]:
# 달의 위상 데이터 프레임의 월명을 숫자로 변환 map 메소드 사용하면 어떤 결과가 나오는지 확인
moon_phases['month'].map(month_mapper).info()

<class 'pandas.Series'>
RangeIndex: 366 entries, 0 to 365
Series name: month
Non-Null Count  Dtype
--------------  -----
366 non-null    int64
dtypes: int64(1)
memory usage: 3.0 KB

In [24]:
# 달의 위상 데이터 프레임의 월명을 숫자로 변환 map 메소드 사용 (month 컬럼에 month_mapper 함수 적용)
moon_phases['month'] = moon_phases['month'].map(month_mapper)
moon_phases.head()

   month  day      moonphase specialevent
0      1    1            NaN          NaN
1      1    2  first quarter          NaN
2      1    3            NaN          NaN
3      1    4            NaN          NaN
4      1    5            NaN          NaN

### 별자리 데이터 프레임

In [25]:
# 별자리 데이터 확인하기
constellations.head()

  constellation bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra    august             90          -40    21:00   northern
1      Aquarius   october             65          -90    21:00   southern
2         Orion   january             85          -75    21:00   northern
3       Perseus  december             90          -35    21:00   northern
4           Leo     april             90           65    21:00   northern

In [26]:
# 별자리 데이터 프레임의 월명을 숫자로 변환 map 메소드 사용하면
constellations['bestmonth'].map(month_mapper).info()

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: bestmonth
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [27]:
# 달의 위상 데이터 프레임의 월명을 숫자로 변환 map 메소드 사용 (month 컬럼에 month_mapper 함수 적용)
constellations['bestmonth'] = constellations['bestmonth'].map(month_mapper)
constellations.head()

  constellation  bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra          8             90          -40    21:00   northern
1      Aquarius         10             65          -90    21:00   southern
2         Orion          1             85          -75    21:00   northern
3       Perseus         12             90          -35    21:00   northern
4           Leo          4             90           65    21:00   northern

In [28]:
constellations.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   constellation  5 non-null      str
 1   bestmonth      5 non-null      int64
 2   latitudestart  5 non-null      int64
 3   latitudeend    5 non-null      int64
 4   besttime       5 non-null      str
 5   hemisphere     5 non-null      str
dtypes: int64(3), str(3)
memory usage: 372.0 bytes

## 새 컬럼(startdate) 생성 - day, month, year 를 결합

### 유성우 데이터 프레임

In [29]:
meteor_showers.head(3)

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,4,4,21,4,22,northern,northern
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern"

In [30]:
# 2020-04-21 => 20200421
test2 = meteor_showers['startday'] + meteor_showers['startmonth'] * 100 + (2020 * 10000)
test2

0    20200421
1    20200419
2    20201002
3    20200714
4    20201106
dtype: int64

In [31]:
meteor_showers['startdate'] = meteor_showers['startday'] + meteor_showers['startmonth'] * 100 + (2020 * 10000)
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere,startdate
0,Lyrids,Lyra,4,4,21,4,22,northern,northern,20200421
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern,20200419
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern",20201002
3,Perseids,Perseus,8,7,14,8,24,northern,northern,20200714
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern",20201106

In [32]:
pd.to_datetime(meteor_showers['startdate'], format='%Y%m%d')

0   2020-04-21
1   2020-04-19
2   2020-10-02
3   2020-07-14
4   2020-11-06
Name: startdate, dtype: datetime64[us]

In [33]:
# 유성우 데이터 프레임의 일자 정보를 datatime 으로 변환하여 새로운 컬럼(startdate)에 저장
meteor_showers['startdate'] = pd.to_datetime(meteor_showers['startdate'], format='%Y%m%d')
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere,startdate
0,Lyrids,Lyra,4,4,21,4,22,northern,northern,2020-04-21
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern,2020-04-19
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern",2020-10-02
3,Perseids,Perseus,8,7,14,8,24,northern,northern,2020-07-14
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern",2020-11-06

In [34]:
# 유성우 데이터 프레임의 일자 정보를 datatime 으로 변환하여 새로운 컬럼(enddate)에 저장
meteor_showers['enddate'] = meteor_showers['endday'] + meteor_showers['endmonth'] * 100 + (2020 * 10000)
meteor_showers['enddate'] = pd.to_datetime(meteor_showers['enddate'], format='%Y%m%d')
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere,startdate,enddate
0,Lyrids,Lyra,4,4,21,4,22,northern,northern,2020-04-21,2020-04-22
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern,2020-04-19,2020-05-28
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern",2020-10-02,2020-11-07
3,Perseids,Perseus,8,7,14,8,24,northern,northern,2020-07-14,2020-08-24
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern",2020-11-06,2020-11-30

### 달의 위상 데이터 프레임

In [35]:
moon_phases.head(3)

   month  day      moonphase specialevent
0      1    1            NaN          NaN
1      1    2  first quarter          NaN
2      1    3            NaN          NaN

In [36]:
# 달의 위상 데이터 프레임의 일자 정보를 datatime으로 변환하여 새로운 컬럼(date)에 저장
moon_phases['date'] = + moon_phases['day'] + moon_phases['month'] * 100 + (2020 * 10000)
moon_phases['date'] = pd.to_datetime(moon_phases['date'], format='%Y%m%d')
moon_phases

     month  day      moonphase specialevent       date
0        1    1            NaN          NaN 2020-01-01
1        1    2  first quarter          NaN 2020-01-02
2        1    3            NaN          NaN 2020-01-03
3        1    4            NaN          NaN 2020-01-04
4        1    5            NaN          NaN 2020-01-05
..     ...  ...            ...          ...        ...
361     12   27            NaN          NaN 2020-12-27
362     12   28            NaN          NaN 2020-12-28
363     12   29      full moon          NaN 2020-12-29
364     12   30            NaN          NaN 2020-12-30
365     12   31            NaN          NaN 2020-12-31

[366 rows x 5 columns]

## 달의 위상을 숫자로 변환

In [37]:
moon_phases['moonphase'].unique()
# moonphases.csv 파일을 열어보면 다음과 같은 주기로 달의 위상이 변한다.
# new moon(삭) -> first quarter(상현달) -> full moon(보름달) -> third quarter(하현달)

<StringArray>
[nan, 'first quarter', 'full moon', 'third quarter', 'new moon']
Length: 5, dtype: str

In [38]:
# 달의 위상 데이터를 숫자로 변환하기
phases = {'new moon': 0, 'first quarter': 0.5, 'third quarter': 0.5, 'full moon': 1}
phases

{'new moon': 0, 'first quarter': 0.5, 'third quarter': 0.5, 'full moon': 1}

In [39]:
moonphase_mapper = lambda x: phases.get(x, x)

In [40]:
# moonphase_mapper 람다 함수 테스트
for phase in phases.keys():
    print(f'{phase} -> {moonphase_mapper(phase)}')

new moon -> 0
first quarter -> 0.5
third quarter -> 0.5
full moon -> 1

In [41]:
# moonphase_mapper 람다 함수 테스트 결과 확인
moon_phases['moonphase'].map(moonphase_mapper)

0      NaN
1      0.5
2      NaN
3      NaN
4      NaN
      ...
361    NaN
362    NaN
363    1.0
364    NaN
365    NaN
Name: moonphase, Length: 366, dtype: float64

In [42]:
# 달의 위상 데이터 프레임에 moonphase 컬럼을 이용하여 백분율 컬럼(percentage) 새롭게 추가하기
moon_phases['percentage'] = moon_phases['moonphase'].map(moonphase_mapper)
moon_phases

     month  day      moonphase specialevent       date  percentage
0        1    1            NaN          NaN 2020-01-01         NaN
1        1    2  first quarter          NaN 2020-01-02         0.5
2        1    3            NaN          NaN 2020-01-03         NaN
3        1    4            NaN          NaN 2020-01-04         NaN
4        1    5            NaN          NaN 2020-01-05         NaN
..     ...  ...            ...          ...        ...         ...
361     12   27            NaN          NaN 2020-12-27         NaN
362     12   28            NaN          NaN 2020-12-28         NaN
363     12   29      full moon          NaN 2020-12-29         1.0
364     12   30            NaN          NaN 2020-12-30         NaN
365     12   31            NaN          NaN 2020-12-31         NaN

[366 rows x 6 columns]

## 불필요한 컬럼 삭제

### 유성우 데이터 프레임

In [43]:
meteor_showers.head(3)

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere,startdate,enddate
0,Lyrids,Lyra,4,4,21,4,22,northern,northern,2020-04-21,2020-04-22
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern,2020-04-19,2020-05-28
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern",2020-10-02,2020-11-07

In [44]:
# 유성우 데이터 프레임에서 불필요한 컬럼 삭제하기
meteor_showers_dropped = meteor_showers.drop(['startmonth', 'startday', 'endmonth', 'endday', 'hemisphere'], axis=1)
meteor_showers_dropped

           name   radiant  bestmonth preferredhemisphere  startdate    enddate
0        Lyrids      Lyra          4            northern 2020-04-21 2020-04-22
1  Eta Aquarids  Aquarius          5            southern 2020-04-19 2020-05-28
2      Orionids     Orion         10  northern, southern 2020-10-02 2020-11-07
3      Perseids   Perseus          8            northern 2020-07-14 2020-08-24
4       Leonids       Leo         11  northern, southern 2020-11-06 2020-11-30

### 달의 위상 데이터 프레임

In [45]:
moon_phases.head(3)

   month  day      moonphase specialevent       date  percentage
0      1    1            NaN          NaN 2020-01-01         NaN
1      1    2  first quarter          NaN 2020-01-02         0.5
2      1    3            NaN          NaN 2020-01-03         NaN

In [46]:
# 달의 위상 데이터 프레임에서 불필요한 컬럼 삭제하기
moon_phases_dropped = moon_phases.drop(['month', 'day',	'moonphase', 'specialevent'], axis=1)
moon_phases_dropped.head(3)

        date  percentage
0 2020-01-01         NaN
1 2020-01-02         0.5
2 2020-01-03         NaN

### 별자리 데이터 프레임

In [47]:
constellations.head(3)

  constellation  bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra          8             90          -40    21:00   northern
1      Aquarius         10             65          -90    21:00   southern
2         Orion          1             85          -75    21:00   northern

In [48]:
# 별자리 데이터 프레임에서 불필요한 컬럼 삭제하기
constellations_dropped = constellations.drop(['besttime'], axis=1)
constellations_dropped

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern
4           Leo          4             90           65   northern

## 달의 위상 누락값 처리

In [49]:
# 달의 위상 데이터 프레임에서 percentage 컬럼의 결측치 처리하기
# 데이터 프레임의 각 행을 순회하면서 이전 위상값으로 채워넣기

# iterrows()를 사용하여 moon_phases 데이터프레임의 각 행을 순차적으로 반복하면서 행(row)과 그 행의 인덱스(index)를 가져온다.
# 결측값인 경우, lastphase에 저장된 값을 해당 행의 'percentage'에 채워 넣는다.
# 즉, 이전에 확인된 마지막 'percentage' 값을 사용하여 결측값을 대체한다.

# 첫번째 행은 데이터가 존재하지 않은데 csv 파일을 열어보면 두번째 행이 'first quarter' 이므로
# 첫번째 행의 percentage 컬럼값은 new moon 에 해당하는 0 이다.

test3 = moon_phases_dropped.copy()

found_first_value = False
for i, row in test3.iterrows():
    if pd.isna(row['percentage']):
        test3.loc[i, 'percentage'] = test3.loc[i-1, 'percentage'] if i > 0 else 0.0

test3

          date  percentage
0   2020-01-01         0.0
1   2020-01-02         0.5
2   2020-01-03         0.5
3   2020-01-04         0.5
4   2020-01-05         0.5
..         ...         ...
361 2020-12-27         0.5
362 2020-12-28         0.5
363 2020-12-29         1.0
364 2020-12-30         1.0
365 2020-12-31         1.0

[366 rows x 2 columns]

In [50]:
# 다음과 같이 처리할 수도 있음
test4 = moon_phases_dropped.copy()

last = 0.0

for i, row in test4.iterrows():
    if pd.isna(row['percentage']):
        test4.loc[i, 'percentage'] = last
    else:
        last = row['percentage']

test4

          date  percentage
0   2020-01-01         0.0
1   2020-01-02         0.5
2   2020-01-03         0.5
3   2020-01-04         0.5
4   2020-01-05         0.5
..         ...         ...
361 2020-12-27         0.5
362 2020-12-28         0.5
363 2020-12-29         1.0
364 2020-12-30         1.0
365 2020-12-31         1.0

[366 rows x 2 columns]

In [51]:
# test3과 test4가 동일한지 확인하기
try:
    pd.testing.assert_frame_equal(test3, test4) # check_like=True
    print("Equal")
except AssertionError as e:
    print("Not equal:", e)

Equal

In [52]:
# 벡터화 방법 (Vectorization) - ffill() 을 사용하는 방법
test5 = moon_phases_dropped.copy()
test5['percentage'].ffill()

0      NaN
1      0.5
2      0.5
3      0.5
4      0.5
      ...
361    0.5
362    0.5
363    1.0
364    1.0
365    1.0
Name: percentage, Length: 366, dtype: float64

In [53]:
# 벡터화 방법 (Vectorization) - ffill() 을 사용하는 방법
test5['percentage'] = test5['percentage'].ffill()
test5

          date  percentage
0   2020-01-01         NaN
1   2020-01-02         0.5
2   2020-01-03         0.5
3   2020-01-04         0.5
4   2020-01-05         0.5
..         ...         ...
361 2020-12-27         0.5
362 2020-12-28         0.5
363 2020-12-29         1.0
364 2020-12-30         1.0
365 2020-12-31         1.0

[366 rows x 2 columns]

In [54]:
# 첫번째 행은 데이터가 존재하지 않으므로 percentage 컬럼의 결측치를 0 으로 채움
test5.loc[0, 'percentage'] = 0.0
test5

          date  percentage
0   2020-01-01         0.0
1   2020-01-02         0.5
2   2020-01-03         0.5
3   2020-01-04         0.5
4   2020-01-05         0.5
..         ...         ...
361 2020-12-27         0.5
362 2020-12-28         0.5
363 2020-12-29         1.0
364 2020-12-30         1.0
365 2020-12-31         1.0

[366 rows x 2 columns]

In [55]:
# test4과 test5가 동일한지 확인하기
try:
    pd.testing.assert_frame_equal(test4, test5) # check_like=True
    print("Equal")
except AssertionError as e:
    print("Not equal:", e)

Equal

In [56]:
# 벡터화 방법 (Vectorization) - ffill() 을 사용하는 방법
test6 = moon_phases_dropped.copy()
test6['percentage'] = test6['percentage'].ffill().bfill()
test6 # test4 와 test5 와 달리 첫번째 행의 NaN 값이 0.5 로 채워짐

          date  percentage
0   2020-01-01         0.5
1   2020-01-02         0.5
2   2020-01-03         0.5
3   2020-01-04         0.5
4   2020-01-05         0.5
..         ...         ...
361 2020-12-27         0.5
362 2020-12-28         0.5
363 2020-12-29         1.0
364 2020-12-30         1.0
365 2020-12-31         1.0

[366 rows x 2 columns]

In [57]:
# test5과 test6가 동일한지 확인하기
# test6 는 bfill 을 호출해서 첫번째 행의 NaN 값이 0.5 로 채워졌기 때문에 test4 나 test5 와는 동일하지 않음
try:
    pd.testing.assert_frame_equal(test5, test6) # check_like=True
    print("Equal")
except AssertionError as e:
    print("Not equal:", e)

Not equal: DataFrame.iloc[:, 1] (column name="percentage") are different

DataFrame.iloc[:, 1] (column name="percentage") values are different (0.27322 %)
[index]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
[left]:  [0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, ...]
[right]: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, ...]
At positional index 0, first diff: 0.0 != 0.5

In [58]:
# 벡터화 방법 (Vectorization) - ffill() 을 사용하는 방법
test7 = moon_phases_dropped.copy()
test7['percentage'] = test7['percentage'].ffill().fillna(0.0)
test7

          date  percentage
0   2020-01-01         0.0
1   2020-01-02         0.5
2   2020-01-03         0.5
3   2020-01-04         0.5
4   2020-01-05         0.5
..         ...         ...
361 2020-12-27         0.5
362 2020-12-28         0.5
363 2020-12-29         1.0
364 2020-12-30         1.0
365 2020-12-31         1.0

[366 rows x 2 columns]

In [59]:
# test5과 test7가 동일한지 확인하기
try:
    pd.testing.assert_frame_equal(test5, test7) # check_like=True
    print("Equal")
except AssertionError as e:
    print("Not equal:", e)

Equal

In [60]:
moon_phases_filled = test7.copy()
moon_phases_filled

          date  percentage
0   2020-01-01         0.0
1   2020-01-02         0.5
2   2020-01-03         0.5
3   2020-01-04         0.5
4   2020-01-05         0.5
..         ...         ...
361 2020-12-27         0.5
362 2020-12-28         0.5
363 2020-12-29         1.0
364 2020-12-30         1.0
365 2020-12-31         1.0

[366 rows x 2 columns]

In [61]:
moon_phases_filled.info()
# 366 개의 데이터 전부가 결측치가 없음을 확인

<class 'pandas.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        366 non-null    datetime64[us]
 1   percentage  366 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 5.8 KB

# 데이터 분석

## 위도 조회
- 목표 : 지정된 도시에서 각 유성우를 볼 수 있는 가능성이 높은 날짜를 예측

In [62]:
# 도시 데이터 프레임에서 검색한 열(검색한 도시의 위도)만 가져오기
# df.loc[조건, 가져올 컬럼 이름] 아래는 'Abu Dhabi'의 결과
cities.loc[cities['city'] == 'Abu Dhabi', 'latitude']

0    24.47
Name: latitude, dtype: float64

### 도시명 입력 후 위도 반환

In [63]:
type(cities.loc[cities['city'] == 'Abu Dhabi', 'latitude'])

pandas.Series

In [64]:
cities.info()

<class 'pandas.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   city      256 non-null    str
 1   latitude  256 non-null    float64
 2   country   256 non-null    str
dtypes: float64(1), str(2)
memory usage: 6.1 KB

In [65]:
test8 = cities[cities['city'] == 'Abu Dhabi']
print(test8)
test8

        city  latitude               country
0  Abu Dhabi     24.47  United Arab Emirates

        city  latitude               country
0  Abu Dhabi     24.47  United Arab Emirates

In [66]:
def find_city(city):
    row = cities[cities['city'] == city]
    if not row.empty:
        print('Exist')
    else:
        print('NotExist')

In [67]:
find_city('Seoul')
find_city('Jeju')

Exist
NotExist

In [68]:
cities.loc[cities['city'] == 'Seoul', 'latitude'].iloc[0]

np.float64(37.55)

In [69]:
# 도시명을 입력하면 위도를 반환하는 함수 만들기
def get_latitude(city_name):
    row = cities.loc[cities['city'] == city_name, 'latitude']
    if not row.empty:
        return row.iloc[0]
    else:
        return None

In [70]:
print(get_latitude('Seoul'))
print(get_latitude('Jeju'))

37.55
None

### 특정 위도에서 볼 수 있는 별자리 조회

In [71]:
constellations_dropped

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern
4           Leo          4             90           65   northern

In [72]:
# 서울에서 관측 가능한 별자리들의 True/False 테이블
seoul_latitude = get_latitude('Seoul') # 37.5
seoul_constellations = (constellations_dropped['latitudeend'] < seoul_latitude) & (seoul_latitude < constellations_dropped['latitudestart'])
seoul_constellations

0     True
1     True
2     True
3     True
4    False
dtype: bool

In [73]:
constellations_dropped

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern
4           Leo          4             90           65   northern

In [74]:
# 서울에서 관측 가능한 별자리들만 출력
constellations_dropped[seoul_constellations]

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern

In [75]:
constellations_dropped[seoul_constellations]['constellation']

0        Lyra
1    Aquarius
2       Orion
3     Perseus
Name: constellation, dtype: str

In [76]:
constellations_dropped[seoul_constellations]['constellation'].to_list()

['Lyra', 'Aquarius', 'Orion', 'Perseus']

In [77]:
def predict_constellations_viewable(city):
    constellations_list = None
    latitude = get_latitude(city)

    if latitude:
        condition1 = latitude >= constellations_dropped['latitudeend']
        condition2 = latitude <= constellations_dropped['latitudestart']
        viewable = (condition1) & (condition2)
        constellations_viewable = constellations_dropped[viewable]

        if not constellations_viewable.empty:
            constellations_list = constellations_viewable['constellation'].to_list()
            return latitude, constellations_list
    
    return latitude, None

In [78]:
print(predict_constellations_viewable('Abu Dhabi'))
print(predict_constellations_viewable('Seoul'))
print(predict_constellations_viewable('Jeju'))
print(predict_constellations_viewable('Wellington'))

(np.float64(24.47), ['Lyra', 'Aquarius', 'Orion', 'Perseus'])
(np.float64(37.55), ['Lyra', 'Aquarius', 'Orion', 'Perseus'])
(None, None)
(np.float64(-41.28), ['Aquarius', 'Orion'])

## 유성우 관측 기간 조회

In [79]:
# 선택한 도시에서 관측 가능한 별자리 추출
wellington_constellations_result = predict_constellations_viewable('Wellington')

print(wellington_constellations_result)
print(wellington_constellations_result[1])
print(wellington_constellations_result[1][0]) # 관측 가능한 첫번째 별자리

(np.float64(-41.28), ['Aquarius', 'Orion'])
['Aquarius', 'Orion']
Aquarius

In [80]:
meteor_showers_dropped

           name   radiant  bestmonth preferredhemisphere  startdate    enddate
0        Lyrids      Lyra          4            northern 2020-04-21 2020-04-22
1  Eta Aquarids  Aquarius          5            southern 2020-04-19 2020-05-28
2      Orionids     Orion         10  northern, southern 2020-10-02 2020-11-07
3      Perseids   Perseus          8            northern 2020-07-14 2020-08-24
4       Leonids       Leo         11  northern, southern 2020-11-06 2020-11-30

In [81]:
meteor_showers_dropped['radiant'] == 'Aquarius'

0    False
1     True
2    False
3    False
4    False
Name: radiant, dtype: bool

In [82]:
meteor_showers_dropped.loc[meteor_showers_dropped['radiant'] == 'Aquarius']

           name   radiant  bestmonth preferredhemisphere  startdate    enddate
1  Eta Aquarids  Aquarius          5            southern 2020-04-19 2020-05-28

In [83]:
wellington_constellations_list = wellington_constellations_result[1]

if wellington_constellations_list:
    constellation = wellington_constellations_list[0] # 관측 가능한 첫번째 별자리
    meteor_showers_viewable = meteor_showers_dropped.loc[meteor_showers_dropped['radiant'] == constellation]
    meteor_showers_startdate = meteor_showers_viewable['startdate'] # 관측 가능한 첫번째 별자리의 유성우 관측 시작일

meteor_showers_startdate

1   2020-04-19
Name: startdate, dtype: datetime64[us]

In [84]:
wellington_constellations_list = wellington_constellations_result[1]

if wellington_constellations_list:
    constellation = wellington_constellations_list[0] # 관측 가능한 첫번째 별자리
    meteor_showers_viewable = meteor_showers_dropped.loc[meteor_showers_dropped['radiant'] == constellation]
    meteor_showers_startdate = meteor_showers_viewable['startdate'] # 관측 가능한 첫번째 별자리의 유성우 관측 시작일
    meteor_showers_startdate = meteor_showers_startdate.iloc[0]

meteor_showers_startdate

Timestamp('2020-04-19 00:00:00')

In [85]:
if wellington_constellations_list:
    constellation = wellington_constellations_list[0] # 관측 가능한 첫번째 별자리
    meteor_showers_viewable = meteor_showers_dropped.loc[meteor_showers_dropped['radiant'] == constellation]
    meteor_showers_enddate = meteor_showers_viewable['enddate'] # 관측 가능한 첫번째 별자리의 유성우 관측 시작일
    meteor_showers_enddate = meteor_showers_enddate.iloc[0]

meteor_showers_enddate

Timestamp('2020-05-28 00:00:00')

## 달의 위상 최소값 추출
- 달의 위상 최소값(달에서 반사되는 빛의 최소량)을 찾을 수 있다.
- 이 예측 함수에서는 첫 번째 날짜만 확인한다.

In [86]:
moon_phases_filled.head(3)

        date  percentage
0 2020-01-01         0.0
1 2020-01-02         0.5
2 2020-01-03         0.5

In [87]:
wellington_condition1 = meteor_showers_startdate <= moon_phases_filled['date']
wellington_condition1

0      False
1      False
2      False
3      False
4      False
       ...
361     True
362     True
363     True
364     True
365     True
Name: date, Length: 366, dtype: bool

In [88]:
wellington_condition2 = meteor_showers_enddate >= moon_phases_filled['date']
wellington_condition2

0       True
1       True
2       True
3       True
4       True
       ...
361    False
362    False
363    False
364    False
365    False
Name: date, Length: 366, dtype: bool

In [89]:
wellington_condition = wellington_condition1 & wellington_condition2
wellington_condition

0      False
1      False
2      False
3      False
4      False
       ...
361    False
362    False
363    False
364    False
365    False
Name: date, Length: 366, dtype: bool

In [90]:
moon_phase_list = moon_phases_filled.loc[wellington_condition]
moon_phase_list.head()

          date  percentage
109 2020-04-19         0.5
110 2020-04-20         0.5
111 2020-04-21         0.5
112 2020-04-22         0.0
113 2020-04-23         0.0

In [91]:
# 가장 어두운 날 찾기 - 달이 보이지 않으므로 가장 관찰하기 좋은 날
moon_phase_list['percentage'].idxmin() # 가장 백분율 값이 작은 행 인덱스 반환

112

In [92]:
best_moon_date = moon_phase_list.loc[moon_phase_list['percentage'].idxmin()]['date']
best_moon_date

Timestamp('2020-04-22 00:00:00')

## 최적의 유성우 관측일

In [93]:
cities.head()

          city  latitude               country
0    Abu Dhabi     24.47  United Arab Emirates
1        Abuja      9.07               Nigeria
2        Accra      5.55                 Ghana
3    Adamstown    -25.07      Pitcairn Islands
4  Addis Ababa      9.02              Ethiopia

In [94]:
cities['city']

0                    Abu Dhabi
1                        Abuja
2                        Accra
3                    Adamstown
4                  Addis Ababa
                ...
251    Abidjan(former capital)
252                    Yaounde
253            Yaren(de facto)
254                    Yerevan
255                     Zagreb
Name: city, Length: 256, dtype: str

In [95]:
cities['city'].values

<StringArray>
[              'Abu Dhabi',                   'Abuja',
                   'Accra',               'Adamstown',
             'Addis Ababa',                 'Algiers',
                   'Alofi',                   'Amman',
               'Amsterdam',        'Andorra la Vella',
 ...
              'Wellington',             'West Island',
              'Willemstad',                'Windhoek',
  'Yamoussoukro(official)', 'Abidjan(former capital)',
                 'Yaounde',         'Yaren(de facto)',
                 'Yerevan',                  'Zagreb']
Length: 256, dtype: str

In [96]:
if 'Seoul' not in cities['city'].values:
    print('입력하신 도시인 Seoul 의 정보를 찾을 수 없습니다.')

if 'Jeju' not in cities['city'].values:
    print('입력하신 도시인 Jeju 의 정보를 찾을 수 없습니다.')

입력하신 도시인 Jeju 의 정보를 찾을 수 없습니다.

In [97]:
print(cities['city'].isin(['Seoul']))

0      False
1      False
2      False
3      False
4      False
       ...
251    False
252    False
253    False
254    False
255    False
Name: city, Length: 256, dtype: bool

In [98]:
print(cities['city'].isin(['Jeju']))

0      False
1      False
2      False
3      False
4      False
       ...
251    False
252    False
253    False
254    False
255    False
Name: city, Length: 256, dtype: bool

In [99]:
print(cities['city'].isin(['Seoul']).any())
print(cities['city'].isin(['Jeju']).any())

True
False

In [100]:
city= 'Seoul'

if city not in cities['city'].values:
    print(f'입력하신 도시인 {city} 의 정보를 찾을 수 없습니다.')
else:
    print(f'입력하신 도시인 {city} 의 정보를 찾을 수 있습니다.')

입력하신 도시인 Seoul 의 정보를 찾을 수 있습니다.

In [101]:
latitude = get_latitude(city)
if not latitude:
    print(f'입력하신 도시인 {city} 의 정보를 찾을 수 없습니다.')
else:
    print(f'입력하신 도시인 {city} 의 정보를 찾을 수 있습니다.')

입력하신 도시인 Seoul 의 정보를 찾을 수 있습니다.

In [102]:
latitude, constellations_list = predict_constellations_viewable(city)
if not latitude:
    print(f'입력하신 도시인 {city} 의 정보를 찾을 수 없습니다.')
else:
    print(f'입력하신 도시인 {city} 의 정보를 찾을 수 있습니다.')

입력하신 도시인 Seoul 의 정보를 찾을 수 있습니다.

In [103]:
# 도시명을 입력하면 관측가능한 유성우에 대한 정보를 알려주는 함수 작성하기
def predict_best_meteor_showers_viewing(city):
    # 입력한 도시 정보가 존재하지 않으면 오류 메시지
    # 방법 1
    # if city not in cities['city'].values:
    #     return f'입력하신 도시인 {city} 의 정보를 찾을 수 없습니다.'
    
    # 도시의 위도 정보를 불러오기
    # 방법 2
    # latitude = get_latitude(city)
    # if not latitude:
    #     return f'입력하신 도시인 {city} 의 정보를 찾을 수 없습니다.'

    # 방법 3
    latitude, constellations_list = predict_constellations_viewable(city)
    if not latitude:
        # print(f'입력하신 도시인 {city} 의 정보를 찾을 수 없습니다.')
        return f'입력하신 도시인 {city} 의 정보를 찾을 수 없습니다.'

    print(f'입력하신 도시인 {city} 의 위도는 {latitude} 입니다.')

    # 해당 도시의 위도에서 관측 가능한 별자리 조회

    # 볼 수 있는 별자리가 존재하지 않으면 오류 메시지
    if not constellations_list:
        return f'입력하신 도시인 {city} 에서 관찰 가능한 별자리가 없습니다.'
    
    # 별자리 관측 가능 안내 메시지
    meteor_showers_string = f'관찰 가능한 별자리는 다음과 같습니다.\n'
    
    # 도시별 관찰 가능한 별자리 iterate
    for constellation in constellations_list:
        # 별자리와 가장 가까운 유성우 조회
        meteor_showers_viewable = meteor_showers_dropped.loc[meteor_showers_dropped['radiant'] == constellation]
        constellation_name = meteor_showers_viewable.iloc[0]['name'] # 별자리 이름
        
        # 유성우 관측이 가능한 시작일과 종료일
        startdate = meteor_showers_viewable.iloc[0]['startdate']
        enddate = meteor_showers_viewable.iloc[0]['enddate']

        # 유성우가 보일 때의 달의 위상 조회
        condition1 = moon_phases_filled['date'] >= startdate
        condition2 = moon_phases_filled['date'] <= enddate
        condition = condition1 & condition2
        moon_phases_meteor_showers = moon_phases_filled.loc[condition]

        # 달이 눈에 보이지 않는 첫째날 조회
        idx = moon_phases_meteor_showers['percentage'].idxmin()
        best_date = moon_phases_meteor_showers.loc[idx, 'date']
        best_date_str = best_date.strftime('%B %d, %Y')
        
        # 사용자에게 정보 전달
        # Lyrids 를 잘 보려면 Lyra 자리 위치를 향하여 April 22, 2020 에 관찰하면 됩니다.
        meteor_showers_string += f'{constellation_name} 를 잘 보려면 {constellation} 자리 위치를 향하여 {best_date_str} 에 관찰하면 됩니다.\n'

    return meteor_showers_string.rstrip()

In [104]:
print(predict_best_meteor_showers_viewing('New York'))

입력하신 도시인 New York 의 정보를 찾을 수 없습니다.

In [105]:
print(predict_best_meteor_showers_viewing('Wellington'))

입력하신 도시인 Wellington 의 위도는 -41.28 입니다.
관찰 가능한 별자리는 다음과 같습니다.
Eta Aquarids 를 잘 보려면 Aquarius 자리 위치를 향하여 April 22, 2020 에 관찰하면 됩니다.
Orionids 를 잘 보려면 Orion 자리 위치를 향하여 October 16, 2020 에 관찰하면 됩니다.

In [106]:
print(predict_best_meteor_showers_viewing('Seoul'))

입력하신 도시인 Seoul 의 위도는 37.55 입니다.
관찰 가능한 별자리는 다음과 같습니다.
Lyrids 를 잘 보려면 Lyra 자리 위치를 향하여 April 22, 2020 에 관찰하면 됩니다.
Eta Aquarids 를 잘 보려면 Aquarius 자리 위치를 향하여 April 22, 2020 에 관찰하면 됩니다.
Orionids 를 잘 보려면 Orion 자리 위치를 향하여 October 16, 2020 에 관찰하면 됩니다.
Perseids 를 잘 보려면 Perseus 자리 위치를 향하여 July 20, 2020 에 관찰하면 됩니다.

# 항아 유성우 데이터 추가

## 유성우

In [107]:
# 항아 유성우 데이터 추가하기
change_meteor_shower = {
    'name' : "Chang\'e",
    'radiant' : 'Draco',
    'bestmonth' : 'october',
    'startmonth': 'october',
    'startday' : 1,
    'endmonth' : 'october',
    'endday' : 31,
    'hemisphere' : 'northern',
    'preferredhemisphere' : 'northern'
}

change_meteor_shower_df = pd.DataFrame(change_meteor_shower, index = [0])
change_meteor_shower_df

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Chang'e,Draco,october,october,1,october,31,northern,northern

In [108]:
# meteorshowers.csv 파일 읽어와서 new_meteor_showers 변수에 저장
new_meteor_showers = pd.read_csv('../data/meteorshowers.csv')
new_meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"

In [109]:
# new_meteor_showers 데이터 프레임에 change_meteor_shower_df 데이터프레임 추가하기 concat
pd.concat([new_meteor_showers, change_meteor_shower_df])

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"
0,Chang'e,Draco,october,october,1,october,31,northern,northern

In [110]:
# index 값이 0, 1, 2, 3, 4, 0 으로 매겨지기 때문에
# ignore_index=True 를 설정해서 index 를 처음부터 다시 매긴다.
pd.concat([new_meteor_showers, change_meteor_shower_df], ignore_index=True)

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"
5,Chang'e,Draco,october,october,1,october,31,northern,northern

In [111]:
# 두 데이터 프레임을 merge 한 최종 파일
new_meteor_showers_merged = pd.concat([new_meteor_showers, change_meteor_shower_df], ignore_index=True)
new_meteor_showers_merged

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"
5,Chang'e,Draco,october,october,1,october,31,northern,northern

In [112]:
new_meteor_showers_merged['bestmonth'].map(month_mapper)

0     4
1     5
2    10
3     8
4    11
5    10
Name: bestmonth, dtype: int64

In [113]:
new_meteor_showers_merged['bestmonth'] = new_meteor_showers_merged['bestmonth'].map(month_mapper)
new_meteor_showers_merged

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,4,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,5,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,10,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,8,july,14,august,24,northern,northern
4,Leonids,Leo,11,november,6,november,30,"northern, southern","northern, southern"
5,Chang'e,Draco,10,october,1,october,31,northern,northern

In [114]:
new_meteor_showers_merged['startmonth'] = new_meteor_showers_merged['startmonth'].map(month_mapper)
new_meteor_showers_merged['endmonth'] = new_meteor_showers_merged['endmonth'].map(month_mapper)
new_meteor_showers_merged

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,4,4,21,4,22,northern,northern
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern"
3,Perseids,Perseus,8,7,14,8,24,northern,northern
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern"
5,Chang'e,Draco,10,10,1,10,31,northern,northern

In [115]:
new_meteor_showers_merged['startdate'] = new_meteor_showers_merged['startday'] + new_meteor_showers_merged['startmonth'] * 100 + (2020 * 10000)
new_meteor_showers_merged['enddate'] = new_meteor_showers_merged['endday'] + new_meteor_showers_merged['endmonth'] * 100 + (2020 * 10000)
new_meteor_showers_merged

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere,startdate,enddate
0,Lyrids,Lyra,4,4,21,4,22,northern,northern,20200421,20200422
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern,20200419,20200528
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern",20201002,20201107
3,Perseids,Perseus,8,7,14,8,24,northern,northern,20200714,20200824
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern",20201106,20201130
5,Chang'e,Draco,10,10,1,10,31,northern,northern,20201001,20201031

In [116]:
new_meteor_showers_merged['startdate'] = pd.to_datetime(new_meteor_showers_merged['startdate'], format='%Y%m%d')
new_meteor_showers_merged['enddate'] = pd.to_datetime(new_meteor_showers_merged['enddate'], format='%Y%m%d')
new_meteor_showers_merged

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere,startdate,enddate
0,Lyrids,Lyra,4,4,21,4,22,northern,northern,2020-04-21,2020-04-22
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern,2020-04-19,2020-05-28
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern",2020-10-02,2020-11-07
3,Perseids,Perseus,8,7,14,8,24,northern,northern,2020-07-14,2020-08-24
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern",2020-11-06,2020-11-30
5,Chang'e,Draco,10,10,1,10,31,northern,northern,2020-10-01,2020-10-31

In [117]:
# 유성우 데이터 프레임에서 불필요한 컬럼 삭제
new_meteor_showers_dropped = new_meteor_showers_merged.drop(['startmonth', 'startday', 'endmonth', 'endday', 'hemisphere'], axis=1)
new_meteor_showers_dropped

           name   radiant  bestmonth preferredhemisphere  startdate    enddate
0        Lyrids      Lyra          4            northern 2020-04-21 2020-04-22
1  Eta Aquarids  Aquarius          5            southern 2020-04-19 2020-05-28
2      Orionids     Orion         10  northern, southern 2020-10-02 2020-11-07
3      Perseids   Perseus          8            northern 2020-07-14 2020-08-24
4       Leonids       Leo         11  northern, southern 2020-11-06 2020-11-30
5       Chang'e     Draco         10            northern 2020-10-01 2020-10-31

## 별자리

In [118]:
# Chang'e 유성우에 대해 Draconids 유성우가 10월 초에 발생할 가능성이 높은 용자리를 선택한다.
# 용자리 항목 추가하기
draco_constellation = {
    'constellation' : 'Draco',
    'bestmonth' : 'july',
    'latitudestart' : 90,
    'latitudeend' : -15,
    'besttime' : 2100,
    'hemisphere' : 'northern'
}

draco_constellation_df = pd.DataFrame(draco_constellation, index = [0])
draco_constellation_df

  constellation bestmonth  latitudestart  latitudeend  besttime hemisphere
0         Draco      july             90          -15      2100   northern

In [119]:
# 별자리 파일을 읽어와서 new_constellations 에 저장하기
new_constellations = pd.read_csv('../data/constellations.csv')
new_constellations

  constellation bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra    august             90          -40    21:00   northern
1      Aquarius   october             65          -90    21:00   southern
2         Orion   january             85          -75    21:00   northern
3       Perseus  december             90          -35    21:00   northern
4           Leo     april             90           65    21:00   northern

In [120]:
# new_constellations 데이터 프레임에 draco_constellation_df 추가하기 concat
new_constellations_merged = pd.concat([new_constellations, draco_constellation_df], ignore_index=True)
new_constellations_merged

  constellation bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra    august             90          -40    21:00   northern
1      Aquarius   october             65          -90    21:00   southern
2         Orion   january             85          -75    21:00   northern
3       Perseus  december             90          -35    21:00   northern
4           Leo     april             90           65    21:00   northern
5         Draco      july             90          -15     2100   northern

In [121]:
new_constellations_merged['bestmonth'].map(month_mapper)

0     8
1    10
2     1
3    12
4     4
5     7
Name: bestmonth, dtype: int64

In [122]:
new_constellations_merged['bestmonth'] = new_constellations_merged['bestmonth'].map(month_mapper)
new_constellations_merged

  constellation  bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra          8             90          -40    21:00   northern
1      Aquarius         10             65          -90    21:00   southern
2         Orion          1             85          -75    21:00   northern
3       Perseus         12             90          -35    21:00   northern
4           Leo          4             90           65    21:00   northern
5         Draco          7             90          -15     2100   northern

In [123]:
# 별자리 데이터 프레임에서 불필요한 컬럼 삭제하기
new_constellations_dropped = new_constellations_merged.drop(['besttime'], axis=1)
new_constellations_dropped

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern
4           Leo          4             90           65   northern
5         Draco          7             90          -15   northern

In [124]:
def predict_constellations_viewable2(df, city):
    latitude = get_latitude(city)

    if latitude:
        condition1 = latitude >= df['latitudeend']
        condition2 = latitude <= df['latitudestart']
        viewable = (condition1) & (condition2)
        constellations_viewable = df[viewable]

        if not constellations_viewable.empty:
            constellations_list = constellations_viewable['constellation'].to_list()
            return latitude, constellations_list
    
    return latitude, None

In [125]:
print(predict_constellations_viewable2(new_constellations_dropped, 'Beijing'))

(np.float64(39.9), ['Lyra', 'Aquarius', 'Orion', 'Perseus', 'Draco'])

In [126]:
# 도시명을 입력하면 관측가능한 유성우에 대한 정보를 알려주는 함수 작성하기
def predict_best_meteor_showers_viewing2(city):
    # 입력한 도시 정보가 존재하지 않으면 오류 메시지
    # 방법 1
    # if city not in cities['city'].values:
    #     return f'입력하신 도시인 {city} 의 정보를 찾을 수 없습니다.'
    
    # 도시의 위도 정보를 불러오기
    # 방법 2
    # latitude = get_latitude(city)
    # if not latitude:
    #     return f'입력하신 도시인 {city} 의 정보를 찾을 수 없습니다.'

    # 방법 3
    latitude, constellations_list = predict_constellations_viewable2(new_constellations_dropped, city)
    if not latitude:
        # print(f'입력하신 도시인 {city} 의 정보를 찾을 수 없습니다.')
        return f'입력하신 도시인 {city} 의 정보를 찾을 수 없습니다.'

    print(f'입력하신 도시인 {city} 의 위도는 {latitude} 입니다.')

    # 해당 도시의 위도에서 관측 가능한 별자리 조회

    # 볼 수 있는 별자리가 존재하지 않으면 오류 메시지
    if not constellations_list:
        return f'입력하신 도시인 {city} 에서 관찰 가능한 별자리가 없습니다.'
    
    # 별자리 관측 가능 안내 메시지
    meteor_showers_string = f'관찰 가능한 별자리는 다음과 같습니다.\n'
    
    # 도시별 관찰 가능한 별자리 iterate
    for constellation in constellations_list:
        # 별자리와 가장 가까운 유성우 조회
        meteor_showers_viewable = new_meteor_showers_dropped.loc[new_meteor_showers_dropped['radiant'] == constellation]
        constellation_name = meteor_showers_viewable.iloc[0]['name'] # 별자리 이름
        
        # 유성우 관측이 가능한 시작일과 종료일
        startdate = meteor_showers_viewable.iloc[0]['startdate']
        enddate = meteor_showers_viewable.iloc[0]['enddate']

        # 유성우가 보일 때의 달의 위상 조회
        condition1 = moon_phases_filled['date'] >= startdate
        condition2 = moon_phases_filled['date'] <= enddate
        condition = condition1 & condition2
        moon_phases_meteor_showers = moon_phases_filled.loc[condition]

        # 달이 눈에 보이지 않는 첫째날 조회
        idx = moon_phases_meteor_showers['percentage'].idxmin()
        best_date = moon_phases_meteor_showers.loc[idx, 'date']
        best_date_str = best_date.strftime('%B %d, %Y')
        
        # 사용자에게 정보 전달
        # Lyrids 를 잘 보려면 Lyra 자리 위치를 향하여 April 22, 2020 에 관찰하면 됩니다.
        meteor_showers_string += f'{constellation_name} 를 잘 보려면 {constellation} 자리 위치를 향하여 {best_date_str} 에 관찰하면 됩니다.\n'

    return meteor_showers_string.rstrip()

In [127]:
print(predict_best_meteor_showers_viewing2('Beijing'))

입력하신 도시인 Beijing 의 위도는 39.9 입니다.
관찰 가능한 별자리는 다음과 같습니다.
Lyrids 를 잘 보려면 Lyra 자리 위치를 향하여 April 22, 2020 에 관찰하면 됩니다.
Eta Aquarids 를 잘 보려면 Aquarius 자리 위치를 향하여 April 22, 2020 에 관찰하면 됩니다.
Orionids 를 잘 보려면 Orion 자리 위치를 향하여 October 16, 2020 에 관찰하면 됩니다.
Perseids 를 잘 보려면 Perseus 자리 위치를 향하여 July 20, 2020 에 관찰하면 됩니다.
Chang'e 를 잘 보려면 Draco 자리 위치를 향하여 October 16, 2020 에 관찰하면 됩니다.