In [1]:
!python -m pip install pandas

Requirement already satisfied: pandas in f:\Projects\20260617\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in f:\Projects\20260617\.venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in f:\Projects\20260617\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in f:\Projects\20260617\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in f:\Projects\20260617\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
s = pd.Series([100, 50, 30, 10])
s

0    100
1     50
2     30
3     10
dtype: int64

In [4]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
s.index=['A', 'B', 'O', 'AB']
s

A     100
B      50
O      30
AB     10
dtype: int64

In [8]:
family = [
    ['김철수', 45, '남', 175, 'A'],
    ['이영희', 43, '여', 168, 'B'],
    ['김선우', 13, '남', 160, 'A'],
    ['김지우', 10, '여', 140, 'O'],
    ['김현우', 7, '남', 125, 'AB']
]

df = pd.DataFrame(family)
df.index = ['아빠','엄마','첫째','둘째','셋째']
df

      0   1  2    3   4
아빠  김철수  45  남  175   A
엄마  이영희  43  여  168   B
첫째  김선우  13  남  160   A
둘째  김지우  10  여  140   O
셋째  김현우   7  남  125  AB

In [9]:
df.columns = ['이름', '나이', '성별', '키', '혈액형']
df

     이름  나이 성별    키 혈액형
아빠  김철수  45  남  175   A
엄마  이영희  43  여  168   B
첫째  김선우  13  남  160   A
둘째  김지우  10  여  140   O
셋째  김현우   7  남  125  AB

In [11]:
df2 = df.set_index('이름')
df2

     나이 성별    키 혈액형
이름
김철수  45  남  175   A
이영희  43  여  168   B
김선우  13  남  160   A
김지우  10  여  140   O
김현우   7  남  125  AB

In [12]:
df.set_index('이름', inplace=True)

In [13]:
df

     나이 성별    키 혈액형
이름
김철수  45  남  175   A
이영희  43  여  168   B
김선우  13  남  160   A
김지우  10  여  140   O
김현우   7  남  125  AB

In [17]:
df = pd.read_csv('../data/scores.csv', encoding='cp949')
df

     학번      이름 성별     국어   영어     수학
0  2201    kate  f  100.0   90   95.0
1  2202  olivia  f   90.0   80   75.0
2  2203    emma  f   95.0  100  100.0
3  2204  sophia  f  100.0  100  100.0
4  2205     amy  f    NaN   35   60.0
5  2206   james  m   70.0   75   65.0
6  2207  daniel  m   80.0   90   55.0
7  2208   peter  m   50.0   60    NaN
8  2209   kevin  m  100.0  100   90.0
9  2210    jack  m   90.0   95   70.0

In [18]:
df.set_index('학번', inplace=True)
df

          이름 성별     국어   영어     수학
학번
2201    kate  f  100.0   90   95.0
2202  olivia  f   90.0   80   75.0
2203    emma  f   95.0  100  100.0
2204  sophia  f  100.0  100  100.0
2205     amy  f    NaN   35   60.0
2206   james  m   70.0   75   65.0
2207  daniel  m   80.0   90   55.0
2208   peter  m   50.0   60    NaN
2209   kevin  m  100.0  100   90.0
2210    jack  m   90.0   95   70.0

In [19]:
df.head(3)

          이름 성별     국어   영어     수학
학번
2201    kate  f  100.0   90   95.0
2202  olivia  f   90.0   80   75.0
2203    emma  f   95.0  100  100.0

In [20]:
df.tail(3)

         이름 성별     국어   영어    수학
학번
2208  peter  m   50.0   60   NaN
2209  kevin  m  100.0  100  90.0
2210   jack  m   90.0   95  70.0

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 2201 to 2210
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      10 non-null     str
 1   성별      10 non-null     str
 2   국어      9 non-null      float64
 3   영어      10 non-null     int64
 4   수학      9 non-null      float64
dtypes: float64(2), int64(1), str(2)
memory usage: 532.0 bytes

In [22]:
df.describe()

               국어          영어          수학
count    9.000000   10.000000    9.000000
mean    86.111111   82.500000   78.888889
std     16.914819   21.114766   17.638342
min     50.000000   35.000000   55.000000
25%     80.000000   76.250000   65.000000
50%     90.000000   90.000000   75.000000
75%    100.000000   98.750000   95.000000
max    100.000000  100.000000  100.000000