In [1]:
!python -m pip install pandas

Requirement already satisfied: pandas in f:\Projects\20260617\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in f:\Projects\20260617\.venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in f:\Projects\20260617\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in f:\Projects\20260617\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in f:\Projects\20260617\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
s = pd.Series([100, 50, 30, 10])
s

0    100
1     50
2     30
3     10
dtype: int64

In [4]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
s.index=['A', 'B', 'O', 'AB']
s

A     100
B      50
O      30
AB     10
dtype: int64

In [8]:
family = [
    ['김철수', 45, '남', 175, 'A'],
    ['이영희', 43, '여', 168, 'B'],
    ['김선우', 13, '남', 160, 'A'],
    ['김지우', 10, '여', 140, 'O'],
    ['김현우', 7, '남', 125, 'AB']
]

df = pd.DataFrame(family)
df.index = ['아빠','엄마','첫째','둘째','셋째']
df

      0   1  2    3   4
아빠  김철수  45  남  175   A
엄마  이영희  43  여  168   B
첫째  김선우  13  남  160   A
둘째  김지우  10  여  140   O
셋째  김현우   7  남  125  AB

In [9]:
df.columns = ['이름', '나이', '성별', '키', '혈액형']
df

     이름  나이 성별    키 혈액형
아빠  김철수  45  남  175   A
엄마  이영희  43  여  168   B
첫째  김선우  13  남  160   A
둘째  김지우  10  여  140   O
셋째  김현우   7  남  125  AB

In [11]:
df2 = df.set_index('이름')
df2

     나이 성별    키 혈액형
이름
김철수  45  남  175   A
이영희  43  여  168   B
김선우  13  남  160   A
김지우  10  여  140   O
김현우   7  남  125  AB

In [12]:
df.set_index('이름', inplace=True)

In [13]:
df

     나이 성별    키 혈액형
이름
김철수  45  남  175   A
이영희  43  여  168   B
김선우  13  남  160   A
김지우  10  여  140   O
김현우   7  남  125  AB

In [17]:
df = pd.read_csv('../data/scores.csv', encoding='cp949')
df

     학번      이름 성별     국어   영어     수학
0  2201    kate  f  100.0   90   95.0
1  2202  olivia  f   90.0   80   75.0
2  2203    emma  f   95.0  100  100.0
3  2204  sophia  f  100.0  100  100.0
4  2205     amy  f    NaN   35   60.0
5  2206   james  m   70.0   75   65.0
6  2207  daniel  m   80.0   90   55.0
7  2208   peter  m   50.0   60    NaN
8  2209   kevin  m  100.0  100   90.0
9  2210    jack  m   90.0   95   70.0

In [18]:
df.set_index('학번', inplace=True)
df

          이름 성별     국어   영어     수학
학번
2201    kate  f  100.0   90   95.0
2202  olivia  f   90.0   80   75.0
2203    emma  f   95.0  100  100.0
2204  sophia  f  100.0  100  100.0
2205     amy  f    NaN   35   60.0
2206   james  m   70.0   75   65.0
2207  daniel  m   80.0   90   55.0
2208   peter  m   50.0   60    NaN
2209   kevin  m  100.0  100   90.0
2210    jack  m   90.0   95   70.0

In [19]:
df.head(3)

          이름 성별     국어   영어     수학
학번
2201    kate  f  100.0   90   95.0
2202  olivia  f   90.0   80   75.0
2203    emma  f   95.0  100  100.0

In [20]:
df.tail(3)

         이름 성별     국어   영어    수학
학번
2208  peter  m   50.0   60   NaN
2209  kevin  m  100.0  100  90.0
2210   jack  m   90.0   95  70.0

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 2201 to 2210
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      10 non-null     str
 1   성별      10 non-null     str
 2   국어      9 non-null      float64
 3   영어      10 non-null     int64
 4   수학      9 non-null      float64
dtypes: float64(2), int64(1), str(2)
memory usage: 532.0 bytes

In [ ]:
df.describe()

               국어          영어          수학
count    9.000000   10.000000    9.000000
mean    86.111111   82.500000   78.888889
std     16.914819   21.114766   17.638342
min     50.000000   35.000000   55.000000
25%     80.000000   76.250000   65.000000
50%     90.000000   90.000000   75.000000
75%    100.000000   98.750000   95.000000
max    100.000000  100.000000  100.000000

In [23]:
df.dtypes

이름        str
성별        str
국어    float64
영어      int64
수학    float64
dtype: object

In [25]:
df['영어'].var()

np.float64(445.8333333333333)

In [27]:
df.value_counts('국어')

국어
100.0    3
90.0     2
95.0     1
70.0     1
80.0     1
50.0     1
Name: count, dtype: int64

In [ ]:
df.sort_index()

In [29]:
df.sort_values('영어', ascending=False)

          이름 성별     국어   영어     수학
학번
2204  sophia  f  100.0  100  100.0
2203    emma  f   95.0  100  100.0
2209   kevin  m  100.0  100   90.0
2210    jack  m   90.0   95   70.0
2207  daniel  m   80.0   90   55.0
2201    kate  f  100.0   90   95.0
2202  olivia  f   90.0   80   75.0
2206   james  m   70.0   75   65.0
2208   peter  m   50.0   60    NaN
2205     amy  f    NaN   35   60.0

In [32]:
print(type(df['이름']))
df['이름']

<class 'pandas.Series'>

학번
2201      kate
2202    olivia
2203      emma
2204    sophia
2205       amy
2206     james
2207    daniel
2208     peter
2209     kevin
2210      jack
Name: 이름, dtype: str

In [33]:
print(type(df[['이름']]))
df[['이름']]

<class 'pandas.DataFrame'>

          이름
학번
2201    kate
2202  olivia
2203    emma
2204  sophia
2205     amy
2206   james
2207  daniel
2208   peter
2209   kevin
2210    jack

In [35]:
print(type(df.loc[2201]))
df.loc[2201]

<class 'pandas.Series'>

이름     kate
성별        f
국어    100.0
영어       90
수학     95.0
Name: 2201, dtype: object

In [36]:
df.loc[[2201]]

        이름 성별     국어  영어    수학
학번
2201  kate  f  100.0  90  95.0

In [37]:
df.loc[[2201, 2205]]

        이름 성별     국어  영어    수학
학번
2201  kate  f  100.0  90  95.0
2205   amy  f    NaN  35  60.0

In [38]:
df.loc[2203]

이름     emma
성별        f
국어     95.0
영어      100
수학    100.0
Name: 2203, dtype: object

In [39]:
df.loc[2203, ['국어', '영어', '수학']]

국어     95.0
영어    100.0
수학    100.0
Name: 2203, dtype: float64

In [40]:
df.loc[[2201, 2205], '이름']

학번
2201    kate
2205     amy
Name: 이름, dtype: str

In [41]:
df.loc[[2201, 2205], ['이름', '수학']]

        이름    수학
학번
2201  kate  95.0
2205   amy  60.0

In [43]:
df.loc[[2201, 2205], ['국어', '영어', '수학']]

         국어  영어    수학
학번
2201  100.0  90  95.0
2205    NaN  35  60.0

In [48]:
df.loc[2201:2203, '국어']

학번
2201    100.0
2202     90.0
2203     95.0
Name: 국어, dtype: float64

In [49]:
df.iloc[0]

이름     kate
성별        f
국어    100.0
영어       90
수학     95.0
Name: 2201, dtype: object

In [50]:
df.iloc[:, [1, 2, 4]]

     성별     국어     수학
학번
2201  f  100.0   95.0
2202  f   90.0   75.0
2203  f   95.0  100.0
2204  f  100.0  100.0
2205  f    NaN   60.0
2206  m   70.0   65.0
2207  m   80.0   55.0
2208  m   50.0    NaN
2209  m  100.0   90.0
2210  m   90.0   70.0

In [51]:
df.loc[df['국어'] == 100]

          이름 성별     국어   영어     수학
학번
2201    kate  f  100.0   90   95.0
2204  sophia  f  100.0  100  100.0
2209   kevin  m  100.0  100   90.0

In [53]:
scores = df.copy()
scores

          이름 성별     국어   영어     수학
학번
2201    kate  f  100.0   90   95.0
2202  olivia  f   90.0   80   75.0
2203    emma  f   95.0  100  100.0
2204  sophia  f  100.0  100  100.0
2205     amy  f    NaN   35   60.0
2206   james  m   70.0   75   65.0
2207  daniel  m   80.0   90   55.0
2208   peter  m   50.0   60    NaN
2209   kevin  m  100.0  100   90.0
2210    jack  m   90.0   95   70.0

In [55]:
ko = scores['국어'] == 100
en = scores['영어'] == 100
ma = scores['수학'] == 100
scores.loc[(ko) & (en) & (ma)]

          이름 성별     국어   영어     수학
학번
2204  sophia  f  100.0  100  100.0

In [56]:
scores.loc[(ko) | (en) | (ma)]

          이름 성별     국어   영어     수학
학번
2201    kate  f  100.0   90   95.0
2203    emma  f   95.0  100  100.0
2204  sophia  f  100.0  100  100.0
2209   kevin  m  100.0  100   90.0

In [ ]:
scores['평균'] = round((scores['국어']+scores['영어']+scores['수학']) / 3, 1)

In [58]:
scores

          이름 성별     국어   영어     수학     평균
학번
2201    kate  f  100.0   90   95.0   95.0
2202  olivia  f   90.0   80   75.0   81.7
2203    emma  f   95.0  100  100.0   98.3
2204  sophia  f  100.0  100  100.0  100.0
2205     amy  f    NaN   35   60.0    NaN
2206   james  m   70.0   75   65.0   70.0
2207  daniel  m   80.0   90   55.0   75.0
2208   peter  m   50.0   60    NaN    NaN
2209   kevin  m  100.0  100   90.0   96.7
2210    jack  m   90.0   95   70.0   85.0

In [59]:
scores.drop(columns=['평균'])

          이름 성별     국어   영어     수학
학번
2201    kate  f  100.0   90   95.0
2202  olivia  f   90.0   80   75.0
2203    emma  f   95.0  100  100.0
2204  sophia  f  100.0  100  100.0
2205     amy  f    NaN   35   60.0
2206   james  m   70.0   75   65.0
2207  daniel  m   80.0   90   55.0
2208   peter  m   50.0   60    NaN
2209   kevin  m  100.0  100   90.0
2210    jack  m   90.0   95   70.0

In [60]:
scores

          이름 성별     국어   영어     수학     평균
학번
2201    kate  f  100.0   90   95.0   95.0
2202  olivia  f   90.0   80   75.0   81.7
2203    emma  f   95.0  100  100.0   98.3
2204  sophia  f  100.0  100  100.0  100.0
2205     amy  f    NaN   35   60.0    NaN
2206   james  m   70.0   75   65.0   70.0
2207  daniel  m   80.0   90   55.0   75.0
2208   peter  m   50.0   60    NaN    NaN
2209   kevin  m  100.0  100   90.0   96.7
2210    jack  m   90.0   95   70.0   85.0

In [ ]:
scores.drop(columns=['평균'], inplace=True)

In [61]:
scores.isnull()

         이름     성별     국어     영어     수학     평균
학번
2201  False  False  False  False  False  False
2202  False  False  False  False  False  False
2203  False  False  False  False  False  False
2204  False  False  False  False  False  False
2205  False  False   True  False  False   True
2206  False  False  False  False  False  False
2207  False  False  False  False  False  False
2208  False  False  False  False   True   True
2209  False  False  False  False  False  False
2210  False  False  False  False  False  False

In [62]:
scores.isnull().sum()

이름    0
성별    0
국어    1
영어    0
수학    1
평균    2
dtype: int64

In [63]:
scores.dropna()

          이름 성별     국어   영어     수학     평균
학번
2201    kate  f  100.0   90   95.0   95.0
2202  olivia  f   90.0   80   75.0   81.7
2203    emma  f   95.0  100  100.0   98.3
2204  sophia  f  100.0  100  100.0  100.0
2206   james  m   70.0   75   65.0   70.0
2207  daniel  m   80.0   90   55.0   75.0
2209   kevin  m  100.0  100   90.0   96.7
2210    jack  m   90.0   95   70.0   85.0

In [64]:
scores

          이름 성별     국어   영어     수학     평균
학번
2201    kate  f  100.0   90   95.0   95.0
2202  olivia  f   90.0   80   75.0   81.7
2203    emma  f   95.0  100  100.0   98.3
2204  sophia  f  100.0  100  100.0  100.0
2205     amy  f    NaN   35   60.0    NaN
2206   james  m   70.0   75   65.0   70.0
2207  daniel  m   80.0   90   55.0   75.0
2208   peter  m   50.0   60    NaN    NaN
2209   kevin  m  100.0  100   90.0   96.7
2210    jack  m   90.0   95   70.0   85.0

In [65]:
scores.fillna(50)

          이름 성별     국어   영어     수학     평균
학번
2201    kate  f  100.0   90   95.0   95.0
2202  olivia  f   90.0   80   75.0   81.7
2203    emma  f   95.0  100  100.0   98.3
2204  sophia  f  100.0  100  100.0  100.0
2205     amy  f   50.0   35   60.0   50.0
2206   james  m   70.0   75   65.0   70.0
2207  daniel  m   80.0   90   55.0   75.0
2208   peter  m   50.0   60   50.0   50.0
2209   kevin  m  100.0  100   90.0   96.7
2210    jack  m   90.0   95   70.0   85.0

In [66]:
scores

          이름 성별     국어   영어     수학     평균
학번
2201    kate  f  100.0   90   95.0   95.0
2202  olivia  f   90.0   80   75.0   81.7
2203    emma  f   95.0  100  100.0   98.3
2204  sophia  f  100.0  100  100.0  100.0
2205     amy  f    NaN   35   60.0    NaN
2206   james  m   70.0   75   65.0   70.0
2207  daniel  m   80.0   90   55.0   75.0
2208   peter  m   50.0   60    NaN    NaN
2209   kevin  m  100.0  100   90.0   96.7
2210    jack  m   90.0   95   70.0   85.0

In [67]:
scores.fillna({'국어':70, '수학':50})

          이름 성별     국어   영어     수학     평균
학번
2201    kate  f  100.0   90   95.0   95.0
2202  olivia  f   90.0   80   75.0   81.7
2203    emma  f   95.0  100  100.0   98.3
2204  sophia  f  100.0  100  100.0  100.0
2205     amy  f   70.0   35   60.0    NaN
2206   james  m   70.0   75   65.0   70.0
2207  daniel  m   80.0   90   55.0   75.0
2208   peter  m   50.0   60   50.0    NaN
2209   kevin  m  100.0  100   90.0   96.7
2210    jack  m   90.0   95   70.0   85.0

In [68]:
temp2 = scores.fillna({'국어':70, '수학':50})
temp2

          이름 성별     국어   영어     수학     평균
학번
2201    kate  f  100.0   90   95.0   95.0
2202  olivia  f   90.0   80   75.0   81.7
2203    emma  f   95.0  100  100.0   98.3
2204  sophia  f  100.0  100  100.0  100.0
2205     amy  f   70.0   35   60.0    NaN
2206   james  m   70.0   75   65.0   70.0
2207  daniel  m   80.0   90   55.0   75.0
2208   peter  m   50.0   60   50.0    NaN
2209   kevin  m  100.0  100   90.0   96.7
2210    jack  m   90.0   95   70.0   85.0

In [70]:
temp2['평균'] = round((temp2['국어']+temp2['영어']+temp2['수학']) / 3, 1)
temp2

          이름 성별     국어   영어     수학     평균
학번
2201    kate  f  100.0   90   95.0   95.0
2202  olivia  f   90.0   80   75.0   81.7
2203    emma  f   95.0  100  100.0   98.3
2204  sophia  f  100.0  100  100.0  100.0
2205     amy  f   70.0   35   60.0   55.0
2206   james  m   70.0   75   65.0   70.0
2207  daniel  m   80.0   90   55.0   75.0
2208   peter  m   50.0   60   50.0   53.3
2209   kevin  m  100.0  100   90.0   96.7
2210    jack  m   90.0   95   70.0   85.0

In [71]:
scores

          이름 성별     국어   영어     수학     평균
학번
2201    kate  f  100.0   90   95.0   95.0
2202  olivia  f   90.0   80   75.0   81.7
2203    emma  f   95.0  100  100.0   98.3
2204  sophia  f  100.0  100  100.0  100.0
2205     amy  f    NaN   35   60.0    NaN
2206   james  m   70.0   75   65.0   70.0
2207  daniel  m   80.0   90   55.0   75.0
2208   peter  m   50.0   60    NaN    NaN
2209   kevin  m  100.0  100   90.0   96.7
2210    jack  m   90.0   95   70.0   85.0

In [72]:
scores.ffill()

          이름 성별     국어   영어     수학     평균
학번
2201    kate  f  100.0   90   95.0   95.0
2202  olivia  f   90.0   80   75.0   81.7
2203    emma  f   95.0  100  100.0   98.3
2204  sophia  f  100.0  100  100.0  100.0
2205     amy  f  100.0   35   60.0  100.0
2206   james  m   70.0   75   65.0   70.0
2207  daniel  m   80.0   90   55.0   75.0
2208   peter  m   50.0   60   55.0   75.0
2209   kevin  m  100.0  100   90.0   96.7
2210    jack  m   90.0   95   70.0   85.0

In [73]:
scores.bfill()

          이름 성별     국어   영어     수학     평균
학번
2201    kate  f  100.0   90   95.0   95.0
2202  olivia  f   90.0   80   75.0   81.7
2203    emma  f   95.0  100  100.0   98.3
2204  sophia  f  100.0  100  100.0  100.0
2205     amy  f   70.0   35   60.0   70.0
2206   james  m   70.0   75   65.0   70.0
2207  daniel  m   80.0   90   55.0   75.0
2208   peter  m   50.0   60   90.0   96.7
2209   kevin  m  100.0  100   90.0   96.7
2210    jack  m   90.0   95   70.0   85.0